"""add sonar fields to reviews

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-03 17:14:05.700072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('sonar_status', sa.String(length=32), nullable=True))
    op.add_column('reviews', sa.Column('sonar_quality_gate', sa.String(length=16), nullable=True))
    op.add_column('reviews', sa.Column('sonar_result', sa.JSON(), nullable=True))
    op.add_column('reviews', sa.Column('github_review_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'github_review_id')
    op.drop_column('reviews', 'sonar_result')
    op.drop_column('reviews', 'sonar_quality_gate')
    op.drop_column('reviews', 'sonar_status')
    # ### end Alembic commands ###
