"""The core AI review call: takes a PR diff, returns structured findings."""

import json

from openai import OpenAI

from app.core.config import settings

SYSTEM_PROMPT = """\
You are a meticulous senior software engineer doing a pull request code review.
You will be given a unified diff. Review ONLY the changes shown — do not
invent context you can't see. Focus on real correctness bugs, security
issues, and clear logic errors introduced by this diff. Do not nitpick
style, formatting, or naming unless it causes an actual bug. If you find
nothing wrong, return an empty bugs list rather than inventing issues.
"""

REVIEW_JSON_SCHEMA = {
    "type": "object",
    "properties": {
        "summary": {
            "type": "string",
            "description": "2-4 sentence plain-English summary of what this PR "
            "changes and the overall review verdict.",
        },
        "bugs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "file": {
                        "type": "string",
                        "description": "File path from the diff this finding applies to.",
                    },
                    "severity": {
                        "type": "string",
                        "enum": ["low", "medium", "high", "critical"],
                    },
                    "description": {
                        "type": "string",
                        "description": "What the bug is and why it's a problem.",
                    },
                    "suggestion": {
                        "type": "string",
                        "description": "A concrete suggested fix.",
                    },
                },
                "required": ["file", "severity", "description", "suggestion"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["summary", "bugs"],
    "additionalProperties": False,
}

_client: OpenAI | None = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI(api_key=settings.openai_api_key)
    return _client


def run_ai_review(diff: str, pr_title: str) -> dict:
    """Call the LLM with the diff and return a dict matching REVIEW_JSON_SCHEMA."""
    response = _get_client().chat.completions.create(
        model=settings.openai_model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"PR title: {pr_title}\n\nDiff:\n```diff\n{diff}\n```",
            },
        ],
        response_format={
            "type": "json_schema",
            "json_schema": {
                "name": "code_review",
                "schema": REVIEW_JSON_SCHEMA,
                "strict": True,
            },
        },
    )
    return json.loads(response.choices[0].message.content)


_SEVERITY_EMOJI = {"low": "🔵", "medium": "🟡", "high": "🟠", "critical": "🔴"}


def format_review_comment(result: dict, truncated: bool = False) -> str:
    lines = ["## 🤖 AI Code Review", "", result["summary"], ""]

    bugs = result.get("bugs", [])
    if bugs:
        lines.append(f"### Findings ({len(bugs)})")
        lines.append("")
        for bug in bugs:
            emoji = _SEVERITY_EMOJI.get(bug["severity"], "⚪")
            lines.append(f"- {emoji} **{bug['severity'].upper()}** · `{bug['file']}`")
            lines.append(f"  {bug['description']}")
            lines.append(f"  _Suggested fix:_ {bug['suggestion']}")
            lines.append("")
    else:
        lines.append("No issues found in this diff.")
        lines.append("")

    if truncated:
        lines.append(
            f"> ⚠️ This diff was truncated to {settings.max_diff_chars:,} characters "
            "before review — some changes may not have been analyzed."
        )
        lines.append("")

    lines.append(
        "<sub>Automated review generated by CodeReviewAI. Verify findings before relying on them.</sub>"
    )
    return "\n".join(lines)
